name: Build and Deploy

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Set env vars (common)
        run: |      
          echo "REMOTE_HOST="${{ secrets.SSH_HOST }} >> $GITHUB_ENV
          echo "REMOTE_BINAY=target" >> $GITHUB_ENV
          echo "REMOTE_APP_FOLDER=/opt/apache-tomcat-9.0.86/webapps" >> $GITHUB_ENV
          
      - uses: actions/checkout@master
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn clean install

      - name: Compress build
        run: |
          touch build.tar.gz
          tar --exclude=build.tar.gz -zcvf build.tar.gz ./.
          
      - name: Copy build to server
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build.tar.gz
          host: ${{ env.REMOTE_HOST }}
          remote: ${{ env.REMOTE_APP_FOLDER }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

      - name: SSH Decompress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.REMOTE_APP_FOLDER }}
            tar xvzf ./build.tar.gz --directory ./
            rm ./build.tar.gz

      - name: SSH Decompress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.REMOTE_APP_FOLDER }}
            mv JOM.war JOM.war.BAK
            cp ./target/JOM.war ./JOM.war
            
      - name: SSH Start/Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.REMOTE_APP_FOLDER }}
            sudo systemctl restart tomcat
